image: node:12.10.0

pages:
  stages:
      - build
      - deploy

  build:
      stage: build
      script:
      - yarn install
      - yarn build

      artifacts:
          expire_in: 1 hour
          paths:
              - build

  deploy:
      stage: deploy
      script:
          - mv build/* public/
      only:
          - master