image: node:12.10.0
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn build

deploy:
  stage: deploy
  script:
    - mv build/* public/

  only:
    - master
